# Generated by Django 3.1.7 on 2021-05-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.TextField(default=0)),
                ('name', models.TextField()),
                ('start_cmd', models.TextField()),
                ('stop_cmd', models.TextField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('params', models.TextField(null=True)),
                ('color', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.TextField(default=0)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InfinityActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.TextField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.TextField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.TextField(default=0)),
                ('name', models.TextField()),
                ('params', models.TextField()),
                ('color', models.TextField()),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('annotate', models.TextField()),
                ('text', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.action')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.group')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.group'),
        ),
    ]
