# Generated by Django 3.0.6 on 2020-12-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='set',
            new_name='set_id',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='set',
            new_name='set_id',
        ),
        migrations.RenameField(
            model_name='timelineactor',
            old_name='set',
            new_name='set_id',
        ),
    ]
