# Generated by Django 3.1.7 on 2021-05-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfinitActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.TextField(default=0)),
                ('name', models.TextField()),
                ('params', models.TextField()),
                ('color', models.TextField()),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('annotate', models.TextField()),
                ('text', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.action')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.group')),
            ],
        ),
        migrations.DeleteModel(
            name='InfinityActor',
        ),
    ]
