# Generated by Django 3.0.6 on 2020-12-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20201222_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='children',
        ),
        migrations.RemoveField(
            model_name='group',
            name='children',
        ),
        migrations.AddField(
            model_name='action',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='models.Group'),
            preserve_default=False,
        ),
    ]
