# Generated by Django 3.1.4 on 2021-01-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20201222_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='color',
            field=models.TextField(default='#000000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='params',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='start_cmd',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='stop_cmd',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='action',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='models.action'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='annotate',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='color',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='models.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='params',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='set_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='stop',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
