# Generated by Django 3.1.4 on 2021-02-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20210127_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
