# Generated by Django 3.1.7 on 2021-03-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_group_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='color',
            new_name='_color',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='duration',
            new_name='_duration',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='group',
            new_name='_group',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='params',
            new_name='_params',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='start_cmd',
            new_name='_start_cmd',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='stop_cmd',
            new_name='_stop_cmd',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='action',
            new_name='_action',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='annotate',
            new_name='_annotate',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='color',
            new_name='_color',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='group',
            new_name='_group',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='params',
            new_name='_params',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='start',
            new_name='_start',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='stop',
            new_name='_stop',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='text',
            new_name='_text',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='position',
            new_name='_position',
        ),
    ]
