# Generated by Django 3.1.7 on 2021-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20210327_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='_stop_cmd',
            field=models.TextField(null=True),
        ),
    ]
