# Generated by Django 3.1.7 on 2021-03-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20210327_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='_group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='_params',
            new_name='params',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='_start_cmd',
            new_name='start_cmd',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='_stop_cmd',
            new_name='stop_cmd',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='_action',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='_annotate',
            new_name='annotate',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='_group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='_params',
            new_name='params',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='_stop',
            new_name='stop',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='_position',
            new_name='position',
        ),
    ]
