# Generated by Django 3.1.7 on 2021-03-28 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20210327_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.group'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.group'),
        ),
    ]
