# Generated by Django 3.1.7 on 2021-03-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20210328_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='position',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
