# Generated by Django 3.1.7 on 2021-04-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_action_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
