# Generated by Django 3.1.7 on 2021-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20210407_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='infinityactor',
            name='set_id',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='action',
            name='set_id',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='actor',
            name='set_id',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='set_id',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='timelineactor',
            name='set_id',
            field=models.TextField(default=0),
        ),
    ]
